### ISSUE TITLE
Relax defaults in from_header

### ISSUE THREAD

**Issue by kbarbary** [JuliaAstro/WCS.jl#14]
wcslib's header-reading functions take a `relax` argument to read non-standard keywords. `WCS.from_header` exposes this, but makes the default 0, corresponding to strict.

- We should follow astropy.wcs here and make the default correspond to reading all non-standard keywords (see http://docs.astropy.org/en/stable/wcs/relax.html).
- We should also expose the constants `#define`d in wcslib to allow users to more easily fine-tune the behavior if desired.

**Comment by giordano** [comment]
Regarding second point, which kind of constants?  Being macros, are they available to programs interfacing the static library?

**Comment by kbarbary** [comment]
@giordano No, they're only available by `#include`ing the C header from C/C++. In Julia they need to be manually copied. See #15.
