### ISSUE TITLE
Overloading getproperty instead of getindex?

### ISSUE THREAD

**Issue by giordano** [JuliaAstro/WCS.jl#16]
In Julia master it's now possible to do fancy things with `a.b` syntax. I think it could make sense to use this feature in `WCS.jl`, so that fields can be accessed with the more natural syntax `wcs.field`, rather than `wcs[:field]`. What do you think?

It should be easy to deprecate the old syntax in favor of the new one, however I fear that all this will require Julia 0.7.

CC @kbarbary

**Comment by kbarbary** [comment]
Yes, I think WCS.jl is a great use case for this new feature. Obviously we'd have to REQUIRE Julia 0.7, as you say.

I think it makes sense to release a new version of WCS using `getproperty` / `setproperty!` and deprecating the old `wcs[:field]`-style behavior once Julia 0.7 is out.

One thing that requires a bit of thought: a statement like `A = [1.0 0.0; 0.0 1.0]; wcs.cd = A` will actually *copy* the contents of the array `A` into the wcslib C struct. If `wcs` was a pure Julia object without `getproperty` overloading, `wcs.cd === A` would be true, and changes to either `A` or `wcd.cd` would affect both. But in this case, we will have `wcs.cd !== A` and they will be totally independent. This may produce unintuitive results if you don't realize that property overloading is going on.

**Comment by giordano** [comment]
> I think it makes sense to release a new version of WCS using `getproperty` / `setproperty!` and deprecating the old `wcs[:field]`-style behavior once Julia 0.7 is out.

Yes, I agree.

Thanks for sharing the caveat!

**Comment by giordano** [comment]
Implemented in #22
